version: "3"

services:
  db-rewards:
    image: postgres:15
    environment:
      POSTGRES_DB: rewards-squid
      POSTGRES_PASSWORD: postgres
    shm_size: 1gb
    ports:
      - "0.0.0.0:${DB_PORT}:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
